# Generated by Django 3.2.2 on 2021-05-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_brand_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
